// <auto-generated />
namespace SUBSURF_MKN_WellOptimization_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class logActionAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(logActionAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202307120953248_logActionAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
